// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2PrPAKFXvueHvAPwT6M7JEysxsNAs7U',
    appId: '1:672669586045:web:ffd680645552534ba09714',
    messagingSenderId: '672669586045',
    projectId: 'hajjumrahagency-dbbae',
    authDomain: 'hajjumrahagency-dbbae.firebaseapp.com',
    storageBucket: 'hajjumrahagency-dbbae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3AZS3Dfus_CQjfioN99zazQUbBBV9o74',
    appId: '1:672669586045:android:f97f0e1d546ee359a09714',
    messagingSenderId: '672669586045',
    projectId: 'hajjumrahagency-dbbae',
    storageBucket: 'hajjumrahagency-dbbae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2uJQBYCmNZXZUw8QCH12PoQJftfdDrY',
    appId: '1:672669586045:ios:2e00731824062628a09714',
    messagingSenderId: '672669586045',
    projectId: 'hajjumrahagency-dbbae',
    storageBucket: 'hajjumrahagency-dbbae.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );
}
